# Generated by Django 4.0.1 on 2022-02-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productvariant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantprice',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvariantprice',
            name='variant',
            field=models.ManyToManyField(related_name='product_variant_price', to='product.ProductVariant'),
        ),
    ]
